
/* 6° ANO DO FUNDAMENTAL 2 */
export const expectativas6 = [
    {
        codigo: "EF69LP01",
        praticas: "Leitura",
        objetivos: ["Apreciação e réplica", "Relação entre gêneros e mídias"],
        habilidades: "Diferenciar liberdade de expressão de discursos de ódio, posicionando-se contrariamente a esse tipo de discurso e vislumbrando possibilidades de denúncia quando for o caso.",
    },
    {
        codigo: "EF69LP02",
        praticas: "Leitura",
        objetivos: ["Apreciação e réplica", "Relação entre gêneros e mídias"],
        habilidades: "Analisar e comparar peças publicitárias variadas (cartazes, folhetos, outdoor, anúncios e propagandas em diferentes mídias, spots, jingle, vídeos etc.), de forma a perceber a articulação entre elas em campanhas, as especificidades das várias semioses e mídias, a adequação dessas peças ao público-alvo, aos objetivos do anunciante e/ou da campanha e à construção composicional e estilo dos gêneros em questão, como forma de ampliar suas possibilidades de compreensão (e produção) de textos pertencentes a esses gêneros.",
    },
    {
        codigo: "EF69LP03",
        praticas: "Leitura",
        objetivos: "Estratégia de leitura: apreender os sentidos globais do texto",
        habilidades: "Identificar, em notícias, o fato central, suas principais circunstâncias e eventuais decorrências; em reportagens e fotorreportagens o fato ou a temática retratada e a perspectiva de abordagem, em entrevistas os principais temas/subtemas abordados, explicações dadas ou teses defendidas em relação a esses subtemas; em tirinhas, memes, charge, a crítica, ironia ou humor presente.",
    },
    {
        codigo: "EF69LP04",
        praticas: "Leitura",
        objetivos: "Efeitos de sentido",
        habilidades: "Identificar e analisar os efeitos de sentido que fortalecem a persuasão nos textos publicitários, relacionando as estratégias de persuasão e apelo ao consumo com os recursos linguístico-discursivos utilizados, como imagens, tempo verbal, jogos de palavras, figuras de linguagem etc., com vistas a fomentar práticas de consumo conscientes.",
    },
    {
        codigo: "EF69LP05",
        praticas: "Leitura",
        objetivos: "Efeitos de sentido",
        habilidades: "Inferir e justificar, em textos multissemióticos – tirinhas, charges, memes, gifs etc. –, o efeito de humor, ironia e/ou crítica pelo uso ambíguo de palavras, expressões ou imagens ambíguas, de clichês, de recursos iconográficos, de pontuação etc.",
    },
    {
        codigo: "EF69LP06",
        praticas: "Produções de texto",
        objetivos: "Relação do texto com o contexto de produção e experimentação de papéis sociais",
        habilidades: "Produzir e publicar notícias, fotodenúncias, fotorreportagens, reportagens, reportagens multimidiáticas, infográficos, podcasts noticiosos, entrevistas, cartas de leitor, comentários, artigos de opinião de interesse local ou global, textos de apresentação e apreciação de produção cultural – resenhas e outros próprios das formas de expressão das culturas juvenis, tais como vlogs e podcasts culturais, gameplay, detonado etc.– e cartazes, anúncios, propagandas, spots, jingles de campanhas sociais, dentre outros em várias mídias, vivenciando de forma significativa o papel de repórter, de comentador, de analista, de crítico, de editor ou articulista, de booktuber, de vlogger (vlogueiro) etc., como forma de compreender as condições de produção que envolvem a circulação desses textos e poder participar e vislumbrar possibilidades de participação nas práticas de linguagem do campo jornalístico e do campo midiático de forma ética e responsável, levando-se em consideração o contexto da Web 2.0, que amplia a possibilidade de circulação desses textos e “funde” os papéis de leitor e autor, de consumidor e produtor.",
    },
    {
        codigo: "EF69LP07",
        praticas: "Produções de texto",
        objetivos: "Textualização",
        habilidades: "Produzir textos em diferentes gêneros, considerando sua adequação ao contexto produção e circulação – os enunciadores envolvidos, os objetivos, o gênero, o suporte, a circulação -, ao modo (escrito ou oral; imagem estática ou em movimento etc.), à variedade linguística e/ou semiótica apropriada a esse contexto, à construção da textualidade relacionada às propriedades textuais e do gênero), utilizando estratégias de planejamento, elaboração, revisão, edição, reescrita/redesign e avaliação de textos, para, com a ajuda do professor e a colaboração dos colegas, corrigir e aprimorar as produções realizadas, fazendo cortes, acréscimos, reformulações, correções de concordância, ortografia, pontuação em textos e editando imagens, arquivos sonoros, fazendo cortes, acréscimos, ajustes, acrescentando/alterando efeitos, ordenamentos etc.",
    },
    {
        codigo: "EF69LP08",
        praticas: "Produções de texto",
        objetivos: "Revisão/edição de texto informativo e opinativo",
        habilidades: "Revisar/editar o texto produzido – notícia, reportagem, resenha, artigo de opinião, dentre outros –, tendo em vista sua adequação ao contexto de produção, a mídia em questão, características do gênero, aspectos relativos à textualidade, a relação entre as diferentes semioses, a formatação e uso adequado das ferramentas de edição (de texto, foto, áudio e vídeo, dependendo do caso) e adequação à norma culta.",
    },
    {
        codigo: "EF69LP09",
        praticas: "Produções de texto",
        objetivos: "Planejamento de textos de peças publicitárias de campanhas sociais",
        habilidades: "Planejar uma campanha publicitária sobre questões/problemas, temas, causas significativas para a escola e/ou comunidade, a partir de um levantamento de material sobre o tema ou evento, da definição do público-alvo, do texto ou peça a ser produzido – cartaz, banner, folheto, panfleto, anúncio impresso e para internet, spot, propaganda de rádio, TV etc. –, da ferramenta de edição de texto, áudio ou vídeo que será utilizada, do recorte e enfoque a ser dado, das estratégias de persuasão que serão utilizadas etc.",
    },
    {
        codigo: "EF69LP10",
        praticas: "Oralidade",
        objetivos: "Produção de textos jornalísticos orais",
        habilidades: "Produzir notícias para rádios, TV ou vídeos, podcasts noticiosos e de opinião, entrevistas, comentários, vlogs, jornais radiofônicos e televisivos, dentre outros possíveis, relativos a fato e temas de interesse pessoal, local ou global e textos orais de apreciação e opinião – podcasts e vlogs noticiosos, culturais e de opinião, orientando-se por roteiro ou texto, considerando o contexto de produção e demonstrando domínio dos gêneros.",
    },
    {
        codigo: "EF69LP11",
        praticas: "Oralidade",
        objetivos: "Produção de textos jornalíticos orais",
        habilidades: "Identificar e analisar posicionamentos defendidos e refutados na escuta de interações polêmicas em entrevistas, discussões e debates (televisivo, em sala de aula, em redes sociais etc.), entre outros, e se posicionar frente a eles.",
    },
    {
        codigo: "EF69LP12",
        praticas: "Oralidade",
        objetivos: "Planejamento e produção de textos jornalísticos orais",
        habilidades: "Desenvolver estratégias de planejamento, elaboração, revisão, edição, reescrita/redesign (esses três últimos quando não for situação ao vivo) e avaliação de textos orais, áudio e/ou vídeo, considerando sua adequação aos contextos em que foram produzidos, à forma composicional e estilo de gêneros, a clareza, progressão temática e variedade linguística empregada, os elementos relacionados à fala, tais como modulação de voz, entonação, ritmo, altura e intensidade, respiração etc., os elementos cinésicos, tais como postura corporal, movimentos e gestualidade significativa, expressão facial, contato de olho com plateia etc.",
    },
    {
        codigo: "EF69LP13",
        praticas: "Oralidade",
        objetivos: "Participação em discussões orais de temas controversos de interesse da turma e/ou de relevância social",
        habilidades: "Engajar-se e contribuir com a busca de conclusões comuns relativas a problemas, temas ou questões polêmicas de interesse da turma e/ou de relevância social.",
    },
    {
        codigo: "EF69LP14",
        praticas: "Oralidade",
        objetivos: "Participação em discussões orais de temas controversos de interesse da turma e/ou de relevância social",
        habilidades: "Formular perguntas e decompor, com a ajuda dos colegas e dos professores, tema/questão polêmica, explicações e ou argumentos relativos ao objeto de discussão para análise mais minuciosa e buscar em fontes diversas informações ou dados que permitam analisar partes da questão e compartilhá-los com a turma.",
    },
    {
        codigo: "EF69LP15",
        praticas: "Oralidade",
        objetivos: "Participação em discussões orais de temas controversos de interesse da turma e/ou de relevância social",
        habilidades: "Apresentar argumentos e contra-argumentos coerentes, respeitando os turnos de fala, na participação em discussões sobre temas controversos e/ou polêmicos.",
    },
    {
        codigo: "EF69LP16",
        praticas: "Análise linguística/semiótica",
        objetivos: "Construção composicional",
        habilidades: "Analisar e utilizar as formas de composição dos gêneros jornalísticos da ordem do relatar, tais como notícias (pirâmide invertida no impresso X blocos noticiosos hipertextuais e hipermidiáticos no digital, que também pode contar com imagens de vários tipos, vídeos, gravações de áudio etc.), da ordem do argumentar, tais como artigos de opinião e editorial (contextualização, defesa de tese/opinião e uso de argumentos) e das entrevistas: apresentação e contextualização do entrevistado e do tema, estrutura pergunta e resposta etc.",
    },
    {
        codigo: "EF69LP17",
        praticas: "Análise linguística/semiótica",
        objetivos: "Estilo",
        habilidades: "Perceber e analisar os recursos estilísticos e semióticos dos gêneros jornalísticos e publicitários, os aspectos relativos ao tratamento da informação em notícias, como a ordenação dos eventos, as escolhas lexicais, o efeito de imparcialidade do relato, a morfologia do verbo, em textos noticiosos e argumentativos, reconhecendo marcas de pessoa, número, tempo, modo, a distribuição dos verbos nos gêneros textuais (por exemplo, as formas de pretérito em relatos; as formas de presente e futuro em gêneros argumentativos; as formas de imperativo em gêneros publicitários), o uso de recursos persuasivos em textos argumentativos diversos (como a elaboração do título, escolhas lexicais, construções metafóricas, a explicitação ou a ocultação de fontes de informação) e as estratégias de persuasão e apelo ao consumo com os recursos linguístico-discursivos utilizados (tempo verbal, jogos de palavras, metáforas, imagens).",
    },
    {
        codigo: "EF69LP18",
        praticas: "Análise linguística/semiótica",
        objetivos: "Estilo",
        habilidades: "Utilizar, na escrita/reescrita de textos argumentativos, recursos linguísticos que marquem as relações de sentido entre parágrafos e enunciados do texto e operadores de conexão adequados aos tipos de argumento e à forma de composição de textos argumentativos, de maneira a garantir a coesão, a coerência e a progressão temática nesses textos (“primeiramente, mas, no entanto, em primeiro/segundo/terceiro lugar, finalmente, em conclusão” etc.).",
    },
    {
        codigo: "EF69LP19",
        praticas: "Análise linguística/semiótica",
        objetivos: "Efeito de sentido",
        habilidades: "Analisar, em gêneros orais que envolvam argumentação, os efeitos de sentido de elementos típicos da modalidade falada, como a pausa, a entonação, o ritmo, a gestualidade e expressão facial, as hesitações etc.",
    },
    {
        codigo: "EF69LP20",
        praticas: "Leitura",
        objetivos: "Reconstrução das condições de produção e circulação e adequação do texto à construção composicional e ao estilo de gênero (Lei, código, estatuto, código, regimento etc.)",
        habilidades: "Identificar, tendo em vista o contexto de produção, a forma de organização dos textos normativos e legais, a lógica de hierarquização de seus itens e subitens e suas partes: parte inicial (título – nome e data – e ementa), blocos de artigos (parte, livro, capítulo, seção, subseção), artigos (caput e parágrafos e incisos) e parte final (disposições pertinentes à sua implementação) e analisar efeitos de sentido causados pelo uso de vocabulário técnico, pelo uso do imperativo, de palavras e expressões que indicam circunstâncias, como advérbios e locuções adverbiais, de palavras que indicam generalidade, como alguns pronomes indefinidos, de forma a poder compreender o caráter imperativo, coercitivo e generalista das leis e de outras formas de regulamentação.",
    },
    {
        codigo: "EF69LP21",
        praticas: "Leitura",
        objetivos: "Apreciação e réplica",
        habilidades: "Posicionar-se em relação a conteúdos veiculados em práticas não institucionalizadas de participação social, sobretudo àquelas vinculadas a manifestações artísticas, produções culturais, intervenções urbanas e práticas próprias das culturas juvenis que pretendam denunciar, expor uma problemática ou “convocar” para uma reflexão/ação, relacionando esse texto/produção com seu contexto de produção e relacionando as partes e semioses presentes para a construção de sentidos.",
    },
    {
        codigo: "EF69LP22",
        praticas: "Produção de textos",
        objetivos: "Textualização, revisão e edição",
        habilidades: "Produzir, revisar e editar textos reivindicatórios ou propositivos sobre problemas que afetam a vida escolar ou da comunidade, justificando pontos de vista, reivindicações e detalhando propostas (justificativa, objetivos, ações previstas etc.), levando em conta seu contexto de produção e as características dos gêneros em questão.",
    },
    {
        codigo: "EF69LP23",
        praticas: "Produção de textos",
        objetivos: "Textualização, revisão e edição",
        habilidades: "Contribuir com a escrita de textos normativos, quando houver esse tipo de demanda na escola – regimentos e estatutos de organizações da sociedade civil do âmbito da atuação das crianças e jovens (grêmio livre, clubes de leitura, associações culturais etc.) – e de regras e regulamentos nos vários âmbitos da escola – campeonatos, festivais, regras de convivência etc., levando em conta o contexto de produção e as características dos gêneros em questão.",
    },
    {
        codigo: "EF69LP24",
        praticas: "Oralidade",
        objetivos: "Discussão oral",
        habilidades: " Discutir casos, reais ou simulações, submetidos a juízo, que envolvam (supostos) desrespeitos a artigos, do ECA, do Código de Defesa do Consumidor, do Código Nacional de Trânsito, de regulamentações do mercado publicitário etc., como forma de criar familiaridade com textos legais – seu vocabulário, formas de organização, marcas de estilo etc. -, de maneira a facilitar a compreensão de leis, fortalecer a defesa de direitos, fomentar a escrita de textos normativos (se e quando isso for necessário) e possibilitar a compreensão do caráter interpretativo das leis e as várias perspectivas que podem estar em jogo.",
    },
    {
        codigo: "EF69LP25",
        praticas: "Oralidade",
        objetivos: "Discussão oral",
        habilidades: "Posicionar-se de forma consistente e sustentada em uma discussão, assembleia, reuniões de colegiados da escola, de agremiações e outras situações de apresentação de propostas e defesas de opiniões, respeitando as opiniões contrárias e propostas alternativas e fundamentando seus posicionamentos, no tempo de fala previsto, valendo-se de sínteses e propostas claras e justificadas.",
    },
    {
        codigo: "EF69LP26",
        praticas: "Oralidade",
        objetivos: "Registro",
        habilidades: "Tomar nota em discussões, debates, palestras, apresentação de propostas, reuniões, como forma de documentar o evento e apoiar a própria fala (que pode se dar no momento do evento ou posteriormente, quando, por exemplo, for necessária a retomada dos assuntos tratados em outros contextos públicos, como diante dos representados).",
    },
    {
        codigo: "EF69LP27",
        praticas: "Análise linguística/semiótica",
        objetivos: "Análise de textos legais/normativos, propositivos e revindicatórios",
        habilidades: " Analisar a forma composicional de textos pertencentes a gêneros normativos/jurídicos e a gêneros da esfera política, tais como propostas, programas políticos (posicionamento quanto a diferentes ações a serem propostas, objetivos, ações previstas etc.), propaganda política (propostas e sua sustentação, posicionamento quanto a temas em discussão) e textos reivindicatórios: cartas de reclamação, petição (proposta, suas justificativas e ações a serem adotadas) e suas marcas linguísticas, de forma a incrementar a compreensão de textos pertencentes a esses gêneros e a possibilitar a produção de textos mais adequados e/ou fundamentados quando isso for requerido.",
    },
    {
        codigo: "EF69LP28",
        praticas: "Análise linguística/semiótica",
        objetivos: "Modalização",
        habilidades: `Observar os mecanismos de modalização adequados aos textos jurídicos, as modalidades deônticas, que se referem ao eixo da conduta (obrigatoriedade/permissibilidade) como, por exemplo: Proibição: “Não se deve fumar em recintos fechados.”; Obrigatoriedade: “A vida tem que valer a pena.”; Possibilidade: “É permitido a entrada de menores acompanhados de adultos responsáveis”, e os mecanismos de modalização adequados aos textos políticos e propositivos, as modalidades apreciativas, em que o locutor exprime um juízo de valor (positivo ou negativo) acerca do que enuncia. Por exemplo: “Que belo discurso!”, “Discordo das escolhas de Antônio.” “Felizmente, o buraco ainda não causou acidentes mais graves.”`,
    },
    {
        codigo: "EF69LP29",
        praticas: "Leitura",
        objetivos: "Reconstrução das condições de produção e recepção dos textos e adequação do texto à construção composicional e ao estilo de gênero",
        habilidades: "Refletir sobre a relação entre os contextos de produção dos gêneros de divulgação científica – texto didático, artigo de divulgação científica, reportagem de divulgação científica, verbete de enciclopédia (impressa e digital), esquema, infográfico (estático e animado), relatório, relato multimidiático de campo, podcasts e vídeos variados de divulgação científica etc. – e os aspectos relativos à construção composicional e às marcas linguística características desses gêneros, de forma a ampliar suas possibilidades de compreensão (e produção) de textos pertencentes a esses gêneros.",
    },
    {
        codigo: "EF69LP30",
        praticas: "Leitura",
        objetivos: "Relação entre textos",
        habilidades: "Comparar, com a ajuda do professor, conteúdos, dados e informações de diferentes fontes, levando em conta seus contextos de produção e referências, identificando coincidências, complementaridades e contradições, de forma a poder identificar erros/imprecisões conceituais, compreender e posicionar-se criticamente sobre os conteúdos e informações em questão.",
    },
    {
        codigo: "",
        praticas: "",
        objetivos: "",
        habilidades: "",
    },
    {
        codigo: "",
        praticas: "",
        objetivos: "",
        habilidades: "",
    },
    {
        codigo: "",
        praticas: "",
        objetivos: "",
        habilidades: "",
    },
    {
        codigo: "",
        praticas: "",
        objetivos: "",
        habilidades: "",
    },
    {
        codigo: "",
        praticas: "",
        objetivos: "",
        habilidades: "",
    },
    {
        codigo: "",
        praticas: "",
        objetivos: "",
        habilidades: "",
    },
    {
        codigo: "",
        praticas: "",
        objetivos: "",
        habilidades: "",
    },
    {
        codigo: "",
        praticas: "",
        objetivos: "",
        habilidades: "",
    }
] 